kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-0
  labels:
    type: rook-ceph-rbd
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
    Recycle
  rbd:
    monitors:
    - '10.254.171.18:6789'
    - '10.254.149.154:6789'
    - '10.254.82.101:6789'
    pool: replicapool
    image: foo
    fsType: ext4
    readOnly: false
    user: admin
    keyring: /etc/ceph/keyring