apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume-configmap
spec:
  containers:
    - name: test-configmap-volume
      image: busybox
      args:
        - sleep
        - "86400"
      resources:
        limits:
          memory: "32Mi"
          cpu: "50m"
      volumeMounts:
        - name: java-ui
          mountPath: "/projected-volume"
          readOnly: true
  volumes:
    - name: java-ui
      projected:
        sources:
          - configMap:
              name: ui-config
