apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # user=admin\r\npass=1f2d1e2e67df
  # user-pass.conf: "dXNlcj1hZG1pblxyXG5wYXNzPTFmMmQxZTJlNjdkZg=="
  user: YWRtaW4=
  pass: MWYyZDFlMmU2N2Rm
# Secret 对象要求这些数据必须是经过 Base64 转码的，以免出现明文密码的安全隐患。
# echo -n 'admin' | base64
# echo -n '1f2d1e2e67df' | base64
