apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume-secret
spec:
  containers:
    - name: test-secret-volume
      image: busybox
      args:
        - sleep
        - "86400"
      resources:
        limits:
          memory: "32Mi"
          cpu: "50m"
      volumeMounts:
        - name: mysql-cred
          mountPath: "/projected-volume"
          readOnly: true
  volumes:
    - name: mysql-cred
      projected:
        sources:
          - secret:
              name: mysecret
