apiVersion: v1
kind: Service
metadata:
  name: hostnames
spec:
  type: NodePort
  selector:
    app: hostnames
  ports:
    - name: default
      nodePort: 30000
      protocol: TCP
      port: 80
      targetPort: 80