apiVersion: v1
kind: Service
metadata:
  name: nginx-sc
spec:
  selector:
    app: nginx-sc
  clusterIP: None
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 80